import { writeFile } from 'fs/promises';

// Function to generate a random string of a given length
function generateRandomString(length) {
  const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let result = '';
  for (let i = 0; i < length; i++) {
    result += characters.charAt(Math.floor(Math.random() * characters.length));
  }
  return result;
}

// Generate a 1000-character random string
const randomString = generateRandomString(1000);

// Content of the JS file
const fileContent = `// This file is generated by a script\n\nexport const foo = "${randomString}";\n`;

// Write the content to a file
async function generateFile() {
  try {
    await writeFile('index.js', fileContent);
    console.log('File generated successfully: index.js');
  } catch (error) {
    console.error('Error writing file:', error);
  }
}

// Run the file generation
generateFile();